# Generated by Django 3.0.3 on 2023-01-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='anime',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='anime',
            name='numberOfEpisodesWatched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='numberOfSeasonsWatched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
